default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: singlepoint_builder_development

test:
  <<: *default
  database: singlepoint_builder_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production_primary:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production_cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production_queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production_cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>